# Generated by Django 4.2.6 on 2023-10-19 22:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ciudad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Prevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_prevision', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_rol', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=50, unique=True, verbose_name='Nombre de usuario')),
                ('contraseña_usuario', models.CharField(max_length=30, verbose_name='Contraseña')),
                ('estado_usuario', models.BooleanField(default=False)),
                ('fecha_ultimo_ingreso', models.DateField(blank=True, null=True)),
                ('rol', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='manager.rol')),
            ],
        ),
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('rut_pro', models.IntegerField(primary_key=True, serialize=False, verbose_name='RUT')),
                ('primer_nombre_pro', models.CharField(max_length=50, verbose_name='Primer nombre')),
                ('segundo_nombre_pro', models.CharField(max_length=50, verbose_name='Segundo nombre')),
                ('apellido_paterno_pro', models.CharField(max_length=50, verbose_name='Apellido paterno')),
                ('apellido_materno_pro', models.CharField(max_length=50, verbose_name='Apellido materno')),
                ('direccion_pro', models.CharField(max_length=50, verbose_name='Direccion')),
                ('celular_pro', models.IntegerField(verbose_name='Celular')),
                ('email_pro', models.EmailField(max_length=50, verbose_name='Email')),
                ('tarifa', models.IntegerField(verbose_name='Tarifa')),
                ('estado_pro', models.BooleanField(verbose_name='Estado')),
                ('fecha_registro_pro', models.DateField(default=datetime.datetime(2023, 10, 19, 22, 51, 30, 111497, tzinfo=datetime.timezone.utc), verbose_name='Fecha de registro')),
                ('id_ciudad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manager.ciudad')),
                ('id_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='manager.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('rut_paciente', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='RUT')),
                ('primer_nombre_pac', models.CharField(max_length=50, verbose_name='Primer nombre')),
                ('segundo_nombre_pac', models.CharField(max_length=50, verbose_name='Segundo nombre')),
                ('apellido_paterno_pac', models.CharField(max_length=50, verbose_name='Apellido paterno')),
                ('apellido_materno_pac', models.CharField(max_length=50, verbose_name='Apellido materno')),
                ('orden_apellido', models.BooleanField(default=False, verbose_name='Invertir el orden de los apellidos')),
                ('fecha_nac', models.DateField(verbose_name='Fecha de nacimiento')),
                ('direccion_pac', models.CharField(max_length=50, verbose_name='Direccion')),
                ('celular_pac', models.IntegerField(verbose_name='Celular')),
                ('email_pac', models.EmailField(max_length=50, verbose_name='Email')),
                ('estado_pac', models.BooleanField(verbose_name='Estado')),
                ('fecha_registro_pac', models.DateField(default=datetime.datetime(2023, 10, 19, 22, 51, 30, 114110, tzinfo=datetime.timezone.utc), verbose_name='Fecha de registro')),
                ('nombre_social', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre social')),
                ('id_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='manager.usuario')),
                ('prevision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manager.prevision')),
            ],
        ),
    ]
