# Generated by Django 4.2.6 on 2023-10-15 06:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ciudad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Prevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_prevision', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_rol', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usr', models.CharField(max_length=50)),
                ('contraseña_usr', models.CharField(max_length=30)),
                ('estado_usr', models.BooleanField()),
                ('fecha_ultimo_ingreso', models.DateField()),
                ('id_rol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manager.rol')),
            ],
        ),
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('rut_pro', models.BigIntegerField(max_length=12, primary_key=True, serialize=False)),
                ('primer_nombre_pro', models.CharField(max_length=50)),
                ('segundo_nombre_pro', models.CharField(max_length=50)),
                ('apellido_paterno_pro', models.CharField(max_length=50)),
                ('apellido_materno_pro', models.CharField(max_length=50)),
                ('direccion_pro', models.CharField(max_length=50)),
                ('celular_pro', models.IntegerField(max_length=9)),
                ('email_pro', models.EmailField(max_length=50)),
                ('tarifa', models.IntegerField()),
                ('estado_pro', models.BooleanField()),
                ('fecha_registro_pro', models.DateField(default=datetime.datetime)),
                ('id_ciudad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manager.ciudad')),
                ('id_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='manager.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('rut_paciente', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('primer_nombre_pac', models.CharField(max_length=50)),
                ('segundo_nombre_pac', models.CharField(max_length=50)),
                ('apellido_paterno_pac', models.CharField(max_length=50)),
                ('apellido_materno_pac', models.CharField(max_length=50)),
                ('orden_apellido', models.BooleanField(default=False)),
                ('fecha_nac', models.DateField()),
                ('direccion_pac', models.CharField(max_length=50)),
                ('celular_pac', models.IntegerField(max_length=9)),
                ('email_pac', models.EmailField(max_length=50)),
                ('estado_pac', models.BooleanField()),
                ('fecha_registro_pac', models.DateField(default=datetime.datetime)),
                ('nombre_social', models.CharField(max_length=50, null=True)),
                ('id_prevision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manager.prevision')),
                ('id_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='manager.usuario')),
            ],
        ),
    ]
