# Generated by Django 4.2.6 on 2023-10-15 06:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='fecha_registro_pac',
            field=models.DateField(default=datetime.datetime(2023, 10, 15, 3, 19, 33, 296514)),
        ),
        migrations.AlterField(
            model_name='profesional',
            name='fecha_registro_pro',
            field=models.DateField(default=datetime.datetime(2023, 10, 15, 3, 19, 33, 292376)),
        ),
    ]
