# Generated by Django 4.2.6 on 2023-10-22 01:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import manager.models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_alter_profesional_options_alter_usuario_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bloque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('estado', models.BooleanField()),
                ('hora_ini', models.TimeField()),
                ('hora_fin', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('valor_mensual', models.IntegerField()),
            ],
        ),
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
                ('objects', manager.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_contrato', models.DateField(default=django.utils.timezone.now)),
                ('valor_mensual', models.IntegerField()),
                ('estado', models.BooleanField()),
                ('fecha_ini', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('rut_pro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manager.profesional')),
            ],
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateField(default=django.utils.timezone.now)),
                ('fecha_atencion', models.DateField()),
                ('estado', models.BooleanField()),
                ('tarifa', models.IntegerField()),
                ('bloque', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manager.bloque')),
                ('rut_pa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manager.paciente')),
                ('rut_pro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manager.profesional')),
            ],
        ),
    ]
