# Generated by Django 4.2.6 on 2023-10-15 06:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_alter_paciente_fecha_registro_pac_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='fecha_registro_pac',
            field=models.DateField(default=datetime.datetime(2023, 10, 15, 3, 22, 38, 541431)),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='id_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='manager.usuario'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nombre_social',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profesional',
            name='fecha_registro_pro',
            field=models.DateField(default=datetime.datetime(2023, 10, 15, 3, 22, 38, 537083)),
        ),
    ]
