# Generated by Django 4.2.6 on 2023-10-23 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_bloque_box_alter_usuario_managers_contrato_agenda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='fecha_ultimo_ingreso',
        ),
    ]
