# Generated by Django 4.2.6 on 2023-10-15 06:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_alter_paciente_fecha_registro_pac_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='fecha_registro_pac',
            field=models.DateField(default=datetime.datetime(2023, 10, 15, 3, 24, 28, 724230)),
        ),
        migrations.AlterField(
            model_name='profesional',
            name='fecha_registro_pro',
            field=models.DateField(default=datetime.datetime(2023, 10, 15, 3, 24, 28, 724230)),
        ),
    ]
