# Generated by Django 4.2.6 on 2023-10-27 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_rename_id_usuario_profesional_usuario_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profesional',
            old_name='id_ciudad',
            new_name='ciudad',
        ),
        migrations.AddField(
            model_name='paciente',
            name='ciudad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='manager.ciudad'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='rut_paciente',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='RUT'),
        ),
    ]
