# Generated by Django 4.2.6 on 2023-10-31 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_rename_id_ciudad_profesional_ciudad_paciente_ciudad_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profesional',
            options={},
        ),
    ]
