# Generated by Django 4.2.6 on 2023-10-24 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_remove_usuario_fecha_ultimo_ingreso'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={},
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='rol',
        ),
        migrations.DeleteModel(
            name='Rol',
        ),
    ]
