# Generated by Django 4.2.6 on 2023-10-15 06:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_alter_paciente_fecha_registro_pac_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='contraseña_usr',
            new_name='contraseña_usuario',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='estado_usr',
            new_name='estado_usuario',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='nombre_usr',
            new_name='nombre_usuario',
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fecha_registro_pac',
            field=models.DateField(default=datetime.datetime(2023, 10, 15, 3, 26, 35, 922620)),
        ),
        migrations.AlterField(
            model_name='profesional',
            name='fecha_registro_pro',
            field=models.DateField(default=datetime.datetime(2023, 10, 15, 3, 26, 35, 922620)),
        ),
    ]
