# Generated by Django 4.2.6 on 2023-10-15 07:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_rename_contraseña_usr_usuario_contraseña_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='fecha_registro_pac',
            field=models.DateField(default=datetime.datetime(2023, 10, 15, 4, 43, 24, 698838)),
        ),
        migrations.AlterField(
            model_name='profesional',
            name='fecha_registro_pro',
            field=models.DateField(default=datetime.datetime(2023, 10, 15, 4, 43, 24, 698838)),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='estado_usuario',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecha_ultimo_ingreso',
            field=models.DateField(blank=True, null=True),
        ),
    ]
