# Generated by Django 4.2.6 on 2023-11-08 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_alter_profesional_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agenda',
            old_name='rut_pro',
            new_name='medico',
        ),
        migrations.RenameField(
            model_name='agenda',
            old_name='rut_pa',
            new_name='paciente',
        ),
    ]
