# Generated by Django 4.2.6 on 2023-11-11 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_rename_rut_pro_agenda_medico_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='agenda',
            constraint=models.UniqueConstraint(fields=('fecha_atencion', 'bloque'), name='pk_constraint'),
        ),
    ]
