# Generated by Django 4.2.6 on 2023-10-18 23:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_alter_paciente_fecha_registro_pac_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='id_rol',
            new_name='rol',
        ),
        migrations.AlterField(
            model_name='paciente',
            name='celular_pac',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fecha_registro_pac',
            field=models.DateField(verbose_name=datetime.datetime(2023, 10, 18, 23, 11, 50, 680820, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='profesional',
            name='celular_pro',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='profesional',
            name='fecha_registro_pro',
            field=models.DateField(verbose_name=datetime.datetime(2023, 10, 18, 23, 11, 50, 676472, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='profesional',
            name='rut_pro',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='contraseña_usuario',
            field=models.CharField(max_length=30, verbose_name='Contraseña'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre_usuario',
            field=models.CharField(max_length=50, verbose_name='Nombre de usuario'),
        ),
    ]
