# Generated by Django 4.2.6 on 2023-11-16 04:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_alter_agenda_tarifa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='fecha_atencion',
            field=models.DateField(default=datetime.datetime(2023, 11, 16, 4, 19, 35, 226989, tzinfo=datetime.timezone.utc)),
        ),
    ]
