# Generated by Django 4.2.6 on 2023-11-16 04:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0011_alter_agenda_fecha_atencion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='fecha_atencion',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
