# Generated by Django 4.2.6 on 2023-11-16 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0013_alter_agenda_fecha_atencion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='tarifa',
            field=models.IntegerField(),
        ),
    ]
